// src/renderer/domain/giros-sii.js
// Catálogo SII de actividades económicas (CIIU4) — códigos vigentes desde
// noviembre de 2018. Fuente: SII Chile, "Homologación Completa de
// Actividades Económicas con el CIIU4.CL 2012"
// (https://www.sii.cl/catastro/homologacion_codigos_actividad.pdf),
// parseado y deduplicado por código nuevo CIIU4 → 574 actividades.
//
// Cada entrada: { codigo: '6 dígitos', desc: 'glosa oficial', cat: 'rubro
// usable en la UI' }. La categoría es derivada del prefijo CIIU4 — agrupa
// las actividades en rubros legibles para el selector del wizard.
//
// API expuesta: window.GirosSII = { GIROS, CATEGORIAS, buscar, buscarPorCodigo }

(function () {
  'use strict';

  const GIROS = [
    { codigo: "842200", desc: "Actividades de defensa", cat: "Administración pública" },
    { codigo: "841100", desc: "Actividades de la administración pública en general", cat: "Administración pública" },
    { codigo: "842300", desc: "Actividades de mantenimiento del orden público y de seguridad", cat: "Administración pública" },
    { codigo: "843090", desc: "Otros planes de seguridad social de afiliación obligatoria n.c.p.", cat: "Administración pública" },
    { codigo: "842100", desc: "Relaciones exteriores", cat: "Administración pública" },
    { codigo: "016100", desc: "Actividades de apoyo a la agricultura", cat: "Agropecuaria y pesca" },
    { codigo: "016200", desc: "Actividades de apoyo a la ganadería", cat: "Agropecuaria y pesca" },
    { codigo: "016300", desc: "Actividades poscosecha", cat: "Agropecuaria y pesca" },
    { codigo: "032200", desc: "Acuicultura de agua dulce", cat: "Agropecuaria y pesca" },
    { codigo: "014901", desc: "Apicultura", cat: "Agropecuaria y pesca" },
    { codigo: "017000", desc: "Caza ordinaria y mediante trampas y actividades de servicios conexas", cat: "Agropecuaria y pesca" },
    { codigo: "014601", desc: "Cría de aves de corral para la producción de carne", cat: "Agropecuaria y pesca" },
    { codigo: "014602", desc: "Cría de aves de corral para la producción de huevos", cat: "Agropecuaria y pesca" },
    { codigo: "014200", desc: "Cría de caballos y otros equinos", cat: "Agropecuaria y pesca" },
    { codigo: "014500", desc: "Cría de cerdos", cat: "Agropecuaria y pesca" },
    { codigo: "014102", desc: "Cría de ganado bovino para la producción de carne o como ganado reproductor", cat: "Agropecuaria y pesca" },
    { codigo: "014101", desc: "Cría de ganado bovino para la producción lechera", cat: "Agropecuaria y pesca" },
    { codigo: "014909", desc: "Cría de otros animales n.c.p.", cat: "Agropecuaria y pesca" },
    { codigo: "014410", desc: "Cría de ovejas (ovinos)", cat: "Agropecuaria y pesca" },
    { codigo: "011200", desc: "Cultivo de arroz", cat: "Agropecuaria y pesca" },
    { codigo: "011103", desc: "Cultivo de avena", cat: "Agropecuaria y pesca" },
    { codigo: "011302", desc: "Cultivo de camotes", cat: "Agropecuaria y pesca" },
    { codigo: "011104", desc: "Cultivo de cebada", cat: "Agropecuaria y pesca" },
    { codigo: "012801", desc: "Cultivo de especias", cat: "Agropecuaria y pesca" },
    { codigo: "011901", desc: "Cultivo de flores", cat: "Agropecuaria y pesca" },
    { codigo: "012400", desc: "Cultivo de frutas de pepita y de hueso", cat: "Agropecuaria y pesca" },
    { codigo: "012600", desc: "Cultivo de frutos oleaginosos (incluye el cultivo de aceitunas)", cat: "Agropecuaria y pesca" },
    { codigo: "011306", desc: "Cultivo de hortalizas y melones", cat: "Agropecuaria y pesca" },
    { codigo: "011107", desc: "Cultivo de lupino", cat: "Agropecuaria y pesca" },
    { codigo: "011102", desc: "Cultivo de maíz", cat: "Agropecuaria y pesca" },
    { codigo: "011108", desc: "Cultivo de otras legumbres (excepto porotos y lupino)", cat: "Agropecuaria y pesca" },
    { codigo: "012900", desc: "Cultivo de otras plantas perennes", cat: "Agropecuaria y pesca" },
    { codigo: "011105", desc: "Cultivo de otros cereales (excepto trigo, maíz, avena y cebada)", cat: "Agropecuaria y pesca" },
    { codigo: "012502", desc: "Cultivo de otros frutos y nueces de árboles y arbustos", cat: "Agropecuaria y pesca" },
    { codigo: "011303", desc: "Cultivo de otros tubérculos (excepto papas y camotes)", cat: "Agropecuaria y pesca" },
    { codigo: "011301", desc: "Cultivo de papas", cat: "Agropecuaria y pesca" },
    { codigo: "012802", desc: "Cultivo de plantas aromáticas, medicinales y farmacéuticas", cat: "Agropecuaria y pesca" },
    { codigo: "012700", desc: "Cultivo de plantas con las que se preparan bebidas (incluye el cultivo de café, té y mate)", cat: "Agropecuaria y pesca" },
    { codigo: "011600", desc: "Cultivo de plantas de fibra", cat: "Agropecuaria y pesca" },
    { codigo: "013000", desc: "Cultivo de plantas vivas incluida la producción en viveros (excepto viveros forestales)", cat: "Agropecuaria y pesca" },
    { codigo: "011106", desc: "Cultivo de porotos", cat: "Agropecuaria y pesca" },
    { codigo: "015000", desc: "Cultivo de productos agrícolas en combinación con la cría de animales (explotación mixta)", cat: "Agropecuaria y pesca" },
    { codigo: "011304", desc: "Cultivo de remolacha azucarera", cat: "Agropecuaria y pesca" },
    { codigo: "011111", desc: "Cultivo de semillas de cereales, legumbres y oleaginosas (excepto semillas de raps y maravilla)", cat: "Agropecuaria y pesca" },
    { codigo: "011305", desc: "Cultivo de semillas de hortalizas", cat: "Agropecuaria y pesca" },
    { codigo: "011110", desc: "Cultivo de semillas de maravilla (girasol)", cat: "Agropecuaria y pesca" },
    { codigo: "011109", desc: "Cultivo de semillas de raps", cat: "Agropecuaria y pesca" },
    { codigo: "011500", desc: "Cultivo de tabaco", cat: "Agropecuaria y pesca" },
    { codigo: "011101", desc: "Cultivo de trigo", cat: "Agropecuaria y pesca" },
    { codigo: "012111", desc: "Cultivo de uva destinada a la producción de pisco y aguardiente", cat: "Agropecuaria y pesca" },
    { codigo: "012112", desc: "Cultivo de uva destinada a la producción de vino", cat: "Agropecuaria y pesca" },
    { codigo: "012120", desc: "Cultivo de uva para mesa", cat: "Agropecuaria y pesca" },
    { codigo: "032110", desc: "Cultivo y crianza de peces marinos", cat: "Agropecuaria y pesca" },
    { codigo: "032120", desc: "Cultivo, reproducción y manejo de algas marinas", cat: "Agropecuaria y pesca" },
    { codigo: "011902", desc: "Cultivos forrajeros en praderas mejoradas o sembradas; cultivos suplementarios forrajeros", cat: "Agropecuaria y pesca" },
    { codigo: "021001", desc: "Explotación de viveros forestales", cat: "Agropecuaria y pesca" },
    { codigo: "022000", desc: "Extracción de madera", cat: "Agropecuaria y pesca" },
    { codigo: "024009", desc: "Otros servicios de apoyo a la silvicultura n.c.p.", cat: "Agropecuaria y pesca" },
    { codigo: "031120", desc: "Pesca marítima artesanal", cat: "Agropecuaria y pesca" },
    { codigo: "031110", desc: "Pesca marítima industrial, excepto de barcos factoría", cat: "Agropecuaria y pesca" },
    { codigo: "023000", desc: "Recolección de productos forestales distintos de la madera", cat: "Agropecuaria y pesca" },
    { codigo: "031130", desc: "Recolección y extracción de productos marinos", cat: "Agropecuaria y pesca" },
    { codigo: "032130", desc: "Reproducción y cría de moluscos, crustáceos y gusanos marinos", cat: "Agropecuaria y pesca" },
    { codigo: "024002", desc: "Servicios de corta de madera a cambio de una retribución o por contrata", cat: "Agropecuaria y pesca" },
    { codigo: "024003", desc: "Servicios de extinción y prevención de incendios forestales", cat: "Agropecuaria y pesca" },
    { codigo: "024001", desc: "Servicios de forestación a cambio de una retribución o por contrata", cat: "Agropecuaria y pesca" },
    { codigo: "032140", desc: "Servicios relacionados con la acuicultura marina", cat: "Agropecuaria y pesca" },
    { codigo: "031140", desc: "Servicios relacionados con la pesca marítima", cat: "Agropecuaria y pesca" },
    { codigo: "360000", desc: "Captación, tratamiento y distribución de agua", cat: "Agua y saneamiento" },
    { codigo: "370000", desc: "Evacuación y tratamiento de aguas servidas", cat: "Agua y saneamiento" },
    { codigo: "381100", desc: "Recogida de desechos no peligrosos", cat: "Agua y saneamiento" },
    { codigo: "383001", desc: "Recuperación y reciclamiento de desperdicios y desechos metálicos", cat: "Agua y saneamiento" },
    { codigo: "383009", desc: "Recuperación y reciclamiento de otros desperdicios y desechos n.c.p.", cat: "Agua y saneamiento" },
    { codigo: "383002", desc: "Recuperación y reciclamiento de papel", cat: "Agua y saneamiento" },
    { codigo: "383003", desc: "Recuperación y reciclamiento de vidrio", cat: "Agua y saneamiento" },
    { codigo: "382100", desc: "Tratamiento y eliminación de desechos no peligrosos", cat: "Agua y saneamiento" },
    { codigo: "102050", desc: "Actividades de elaboración y conservación de pescado, realizadas en barcos factoría", cat: "Alimentos y bebidas" },
    { codigo: "110120", desc: "Destilación, rectificación y mezclas de bebidas alcohólicas; excepto pisco", cat: "Alimentos y bebidas" },
    { codigo: "104000", desc: "Elaboración de aceites y grasas de origen vegetal y animal (excepto elaboración de mantequilla)", cat: "Alimentos y bebidas" },
    { codigo: "106200", desc: "Elaboración de almidones y productos derivados del almidón", cat: "Alimentos y bebidas" },
    { codigo: "107200", desc: "Elaboración de azúcar", cat: "Alimentos y bebidas" },
    { codigo: "110300", desc: "Elaboración de bebidas malteadas y de malta", cat: "Alimentos y bebidas" },
    { codigo: "110401", desc: "Elaboración de bebidas no alcohólicas", cat: "Alimentos y bebidas" },
    { codigo: "107300", desc: "Elaboración de cacao, chocolate y de productos de confitería", cat: "Alimentos y bebidas" },
    { codigo: "120001", desc: "Elaboración de cigarros y cigarrillos", cat: "Alimentos y bebidas" },
    { codigo: "107902", desc: "Elaboración de levaduras naturales o artificiales", cat: "Alimentos y bebidas" },
    { codigo: "107400", desc: "Elaboración de macarrones, fideos, alcuzcuz y productos farináceos similares", cat: "Alimentos y bebidas" },
    { codigo: "107909", desc: "Elaboración de otros productos alimenticios n.c.p.", cat: "Alimentos y bebidas" },
    { codigo: "106109", desc: "Elaboración de otros productos de molinería n.c.p.", cat: "Alimentos y bebidas" },
    { codigo: "120009", desc: "Elaboración de otros productos de tabaco n.c.p.", cat: "Alimentos y bebidas" },
    { codigo: "108000", desc: "Elaboración de piensos preparados para animales", cat: "Alimentos y bebidas" },
    { codigo: "110110", desc: "Elaboración de pisco (industrias pisqueras)", cat: "Alimentos y bebidas" },
    { codigo: "107100", desc: "Elaboración de productos de panadería y pastelería", cat: "Alimentos y bebidas" },
    { codigo: "105000", desc: "Elaboración de productos lácteos", cat: "Alimentos y bebidas" },
    { codigo: "107901", desc: "Elaboración de té, café, mate e infusiones de hierbas", cat: "Alimentos y bebidas" },
    { codigo: "107903", desc: "Elaboración de vinagres, mostazas, mayonesas y condimentos en general", cat: "Alimentos y bebidas" },
    { codigo: "110200", desc: "Elaboración de vinos", cat: "Alimentos y bebidas" },
    { codigo: "101020", desc: "Elaboración y conservación de carne y productos cárnicos", cat: "Alimentos y bebidas" },
    { codigo: "103000", desc: "Elaboración y conservación de frutas, legumbres y hortalizas", cat: "Alimentos y bebidas" },
    { codigo: "102030", desc: "Elaboración y conservación de otros pescados, en plantas en tierra (excepto barcos factoría)", cat: "Alimentos y bebidas" },
    { codigo: "102020", desc: "Elaboración y conservación de salmónidos", cat: "Alimentos y bebidas" },
    { codigo: "102060", desc: "Elaboración y procesamiento de algas", cat: "Alimentos y bebidas" },
    { codigo: "101019", desc: "Explotación de mataderos de aves y de otros tipos de animales n.c.p.", cat: "Alimentos y bebidas" },
    { codigo: "101011", desc: "Explotación de mataderos de bovinos, ovinos, equinos, caprinos, porcinos y camélidos", cat: "Alimentos y bebidas" },
    { codigo: "106102", desc: "Molienda de arroz; producción de harina de arroz", cat: "Alimentos y bebidas" },
    { codigo: "106101", desc: "Molienda de trigo: producción de harina, sémola y gránulos", cat: "Alimentos y bebidas" },
    { codigo: "110402", desc: "Producción de aguas minerales y otras aguas embotelladas", cat: "Alimentos y bebidas" },
    { codigo: "102010", desc: "Producción de harina de pescado", cat: "Alimentos y bebidas" },
    { codigo: "551001", desc: "Actividades de hoteles", cat: "Alojamiento" },
    { codigo: "551002", desc: "Actividades de moteles", cat: "Alojamiento" },
    { codigo: "559001", desc: "Actividades de residenciales para estudiantes y trabajadores", cat: "Alojamiento" },
    { codigo: "559009", desc: "Otras actividades de alojamiento n.c.p.", cat: "Alojamiento" },
    { codigo: "773001", desc: "Alquiler de equipos de transporte sin operario, excepto vehículos automotores", cat: "Alquiler y arrendamiento" },
    { codigo: "773002", desc: "Alquiler de maquinaria y equipo agropecuario, forestal, de construcción e ing. civil, sin operarios", cat: "Alquiler y arrendamiento" },
    { codigo: "773003", desc: "Alquiler de maquinaria y equipo de oficina, sin operarios (sin servicio administrativo)", cat: "Alquiler y arrendamiento" },
    { codigo: "772900", desc: "Alquiler de otros efectos personales y enseres domésticos (incluye mobiliario para eventos)", cat: "Alquiler y arrendamiento" },
    { codigo: "773009", desc: "Alquiler de otros tipos de maquinarias y equipos sin operario n.c.p.", cat: "Alquiler y arrendamiento" },
    { codigo: "771000", desc: "Alquiler de vehículos automotores sin chofer", cat: "Alquiler y arrendamiento" },
    { codigo: "772100", desc: "Alquiler y arrendamiento de equipo recreativo y deportivo", cat: "Alquiler y arrendamiento" },
    { codigo: "712001", desc: "Actividades de plantas de revisión técnica para vehículos automotores", cat: "Arquitectura e ingeniería" },
    { codigo: "711002", desc: "Empresas de servicios de ingeniería y actividades conexas de consultoría técnica", cat: "Arquitectura e ingeniería" },
    { codigo: "712009", desc: "Otros servicios de ensayos y análisis técnicos (excepto actividades de plantas de revisión técnica)", cat: "Arquitectura e ingeniería" },
    { codigo: "711001", desc: "Servicios de arquitectura (diseño de edificios, dibujo de planos de construcción, entre otros)", cat: "Arquitectura e ingeniería" },
    { codigo: "711003", desc: "Servicios profesionales de ingeniería y actividades conexas de consultoría técnica", cat: "Arquitectura e ingeniería" },
    { codigo: "900002", desc: "Actividades artísticas realizadas por bandas de música, compañías de teatro, circenses y similares", cat: "Arte, entretenimiento y juegos" },
    { codigo: "900003", desc: "Actividades de artistas realizadas de forma independiente: actores, músicos, escritores, entre otros", cat: "Arte, entretenimiento y juegos" },
    { codigo: "910100", desc: "Actividades de bibliotecas y archivos", cat: "Arte, entretenimiento y juegos" },
    { codigo: "920010", desc: "Actividades de casinos de juegos", cat: "Arte, entretenimiento y juegos" },
    { codigo: "910300", desc: "Actividades de jardines botánicos, zoológicos y reservas naturales", cat: "Arte, entretenimiento y juegos" },
    { codigo: "910200", desc: "Actividades de museos, gestión de lugares y edificios históricos", cat: "Arte, entretenimiento y juegos" },
    { codigo: "920090", desc: "Otras actividades de juegos de azar y apuestas n.c.p.", cat: "Arte, entretenimiento y juegos" },
    { codigo: "900001", desc: "Servicios de producción de obras de teatro, conciertos, espectáculos de danza, otras prod. escénicas", cat: "Arte, entretenimiento y juegos" },
    { codigo: "900004", desc: "Servicios prestados por periodistas independientes", cat: "Arte, entretenimiento y juegos" },
    { codigo: "941100", desc: "Actividades de asociaciones empresariales y de empleadores", cat: "Asociaciones y organizaciones" },
    { codigo: "941200", desc: "Actividades de asociaciones profesionales", cat: "Asociaciones y organizaciones" },
    { codigo: "949901", desc: "Actividades de centros de madres", cat: "Asociaciones y organizaciones" },
    { codigo: "949902", desc: "Actividades de clubes sociales", cat: "Asociaciones y organizaciones" },
    { codigo: "949200", desc: "Actividades de organizaciones políticas", cat: "Asociaciones y organizaciones" },
    { codigo: "949100", desc: "Actividades de organizaciones religiosas", cat: "Asociaciones y organizaciones" },
    { codigo: "949909", desc: "Actividades de otras asociaciones n.c.p.", cat: "Asociaciones y organizaciones" },
    { codigo: "942000", desc: "Actividades de sindicatos", cat: "Asociaciones y organizaciones" },
    { codigo: "949904", desc: "Consejo de administración de edificios y condominios", cat: "Asociaciones y organizaciones" },
    { codigo: "949903", desc: "Fundaciones y corporaciones; asociaciones que promueven actividades culturales o recreativas", cat: "Asociaciones y organizaciones" },
    { codigo: "454003", desc: "Mantenimiento y reparación de motocicletas", cat: "Comercio de vehículos" },
    { codigo: "452002", desc: "Mantenimiento y reparación de vehículos automotores", cat: "Comercio de vehículos" },
    { codigo: "452001", desc: "Servicio de lavado de vehículos automotores", cat: "Comercio de vehículos" },
    { codigo: "451001", desc: "Venta al por mayor de vehículos automotores", cat: "Comercio de vehículos" },
    { codigo: "451002", desc: "Venta al por menor de vehículos automotores nuevos o usados (incluye compraventa)", cat: "Comercio de vehículos" },
    { codigo: "454001", desc: "Venta de motocicletas", cat: "Comercio de vehículos" },
    { codigo: "454002", desc: "Venta de partes, piezas y accesorios de motocicletas", cat: "Comercio de vehículos" },
    { codigo: "453000", desc: "Venta de partes, piezas y accesorios para vehículos automotores", cat: "Comercio de vehículos" },
    { codigo: "461002", desc: "Corretaje al por mayor de ganado", cat: "Comercio mayorista" },
    { codigo: "461001", desc: "Corretaje al por mayor de productos agrícolas", cat: "Comercio mayorista" },
    { codigo: "461009", desc: "Otros tipos de corretajes o remates al por mayor n.c.p.", cat: "Comercio mayorista" },
    { codigo: "462020", desc: "Venta al por mayor de animales vivos", cat: "Comercio mayorista" },
    { codigo: "464904", desc: "Venta al por mayor de artículos de papelería y escritorio", cat: "Comercio mayorista" },
    { codigo: "464903", desc: "Venta al por mayor de artículos de perfumería, de tocador y cosméticos", cat: "Comercio mayorista" },
    { codigo: "464902", desc: "Venta al por mayor de artículos eléctricos y electrónicos para el hogar", cat: "Comercio mayorista" },
    { codigo: "463020", desc: "Venta al por mayor de bebidas alcohólicas y no alcohólicas", cat: "Comercio mayorista" },
    { codigo: "463012", desc: "Venta al por mayor de carne y productos cárnicos", cat: "Comercio mayorista" },
    { codigo: "466100", desc: "Venta al por mayor de combustibles sólidos, líquidos y gaseosos y productos conexos", cat: "Comercio mayorista" },
    { codigo: "465100", desc: "Venta al por mayor de computadores, equipo periférico y programas informáticos", cat: "Comercio mayorista" },
    { codigo: "466902", desc: "Venta al por mayor de desechos metálicos (chatarra)", cat: "Comercio mayorista" },
    { codigo: "466909", desc: "Venta al por mayor de desperdicios, desechos y otros productos n.c.p.", cat: "Comercio mayorista" },
    { codigo: "464906", desc: "Venta al por mayor de diarios y revistas", cat: "Comercio mayorista" },
    { codigo: "465905", desc: "Venta al por mayor de equipo de transporte(excepto vehículos automotores, motocicletas y bicicletas)", cat: "Comercio mayorista" },
    { codigo: "463011", desc: "Venta al por mayor de frutas y verduras", cat: "Comercio mayorista" },
    { codigo: "463019", desc: "Venta al por mayor de huevos, lácteos, abarrotes y de otros alimentos n.c.p.", cat: "Comercio mayorista" },
    { codigo: "464908", desc: "Venta al por mayor de instrumentos científicos y quirúrgicos", cat: "Comercio mayorista" },
    { codigo: "464905", desc: "Venta al por mayor de libros", cat: "Comercio mayorista" },
    { codigo: "466301", desc: "Venta al por mayor de madera en bruto y productos primarios de la elaboración de madera", cat: "Comercio mayorista" },
    { codigo: "465901", desc: "Venta al por mayor de maquinaria metalúrgica, para la minería, extracción de petróleo y construcción", cat: "Comercio mayorista" },
    { codigo: "465902", desc: "Venta al por mayor de maquinaria para la elaboración de alimentos, bebidas y tabaco", cat: "Comercio mayorista" },
    { codigo: "465903", desc: "Venta al por mayor de maquinaria para la industria textil, del cuero y del calzado", cat: "Comercio mayorista" },
    { codigo: "466302", desc: "Venta al por mayor de materiales de construcción, artículos de ferretería, gasfitería y calefacción", cat: "Comercio mayorista" },
    { codigo: "462010", desc: "Venta al por mayor de materias primas agrícolas", cat: "Comercio mayorista" },
    { codigo: "466200", desc: "Venta al por mayor de metales y minerales metalíferos", cat: "Comercio mayorista" },
    { codigo: "464901", desc: "Venta al por mayor de muebles, excepto muebles de oficina", cat: "Comercio mayorista" },
    { codigo: "462090", desc: "Venta al por mayor de otras materias primas agropecuarias n.c.p.", cat: "Comercio mayorista" },
    { codigo: "464909", desc: "Venta al por mayor de otros enseres domésticos n.c.p.", cat: "Comercio mayorista" },
    { codigo: "465909", desc: "Venta al por mayor de otros tipos de maquinaria y equipo n.c.p.", cat: "Comercio mayorista" },
    { codigo: "463014", desc: "Venta al por mayor de productos de confitería", cat: "Comercio mayorista" },
    { codigo: "463013", desc: "Venta al por mayor de productos del mar (pescados, mariscos y algas)", cat: "Comercio mayorista" },
    { codigo: "464907", desc: "Venta al por mayor de productos farmacéuticos y medicinales", cat: "Comercio mayorista" },
    { codigo: "466901", desc: "Venta al por mayor de productos químicos", cat: "Comercio mayorista" },
    { codigo: "464100", desc: "Venta al por mayor de productos textiles, prendas de vestir y calzado", cat: "Comercio mayorista" },
    { codigo: "463030", desc: "Venta al por mayor de tabaco", cat: "Comercio mayorista" },
    { codigo: "469000", desc: "Venta al por mayor no especializada", cat: "Comercio mayorista" },
    { codigo: "471990", desc: "Otras actividades de venta al por menor en comercios no especializados n.c.p.", cat: "Comercio minorista / retail" },
    { codigo: "479909", desc: "Otras actividades de venta por menor no realizadas en comercios, puestos de venta o mercados n.c.p.", cat: "Comercio minorista / retail" },
    { codigo: "477391", desc: "Venta al por menor de alimento y accesorios para mascotas en comercios especializados", cat: "Comercio minorista / retail" },
    { codigo: "472101", desc: "Venta al por menor de alimentos en comercios especializados (almacenes pequeños y minimarket)", cat: "Comercio minorista / retail" },
    { codigo: "478100", desc: "Venta al por menor de alimentos, bebidas y tabaco en puestos de venta y mercados (incluye ferias)", cat: "Comercio minorista / retail" },
    { codigo: "477401", desc: "Venta al por menor de antigüedades en comercios", cat: "Comercio minorista / retail" },
    { codigo: "475909", desc: "Venta al por menor de aparatos eléctricos, textiles para el hogar y otros enseres domésticos n.c.p.", cat: "Comercio minorista / retail" },
    { codigo: "476301", desc: "Venta al por menor de artículos de caza y pesca en comercios especializados", cat: "Comercio minorista / retail" },
    { codigo: "475201", desc: "Venta al por menor de artículos de ferretería y materiales de construcción", cat: "Comercio minorista / retail" },
    { codigo: "477394", desc: "Venta al por menor de artículos de joyería, bisutería y relojería en comercios especializados", cat: "Comercio minorista / retail" },
    { codigo: "476103", desc: "Venta al por menor de artículos de papelería y escritorio en comercios especializados", cat: "Comercio minorista / retail" },
    { codigo: "477203", desc: "Venta al por menor de artículos de perfumería, de tocador y cosméticos en comercios especializados", cat: "Comercio minorista / retail" },
    { codigo: "477202", desc: "Venta al por menor de artículos ortopédicos en comercios especializados", cat: "Comercio minorista / retail" },
    { codigo: "477393", desc: "Venta al por menor de artículos ópticos en comercios especializados", cat: "Comercio minorista / retail" },
    { codigo: "472200", desc: "Venta al por menor de bebidas alcohólicas y no alcohólicas en comercios especializados (botillerías)", cat: "Comercio minorista / retail" },
    { codigo: "476302", desc: "Venta al por menor de bicicletas y sus repuestos en comercios especializados", cat: "Comercio minorista / retail" },
    { codigo: "477101", desc: "Venta al por menor de calzado en comercios especializados", cat: "Comercio minorista / retail" },
    { codigo: "477395", desc: "Venta al por menor de carbón, leña y otros combustibles de uso doméstico en comercios especializados", cat: "Comercio minorista / retail" },
    { codigo: "477103", desc: "Venta al por menor de carteras, maletas y otros accesorios de viaje en comercios especializados", cat: "Comercio minorista / retail" },
    { codigo: "473000", desc: "Venta al por menor de combustibles para vehículos automotores en comercios especializados", cat: "Comercio minorista / retail" },
    { codigo: "474100", desc: "Venta al por menor de computadores, equipo periférico, programas informáticos y equipo de telecom.", cat: "Comercio minorista / retail" },
    { codigo: "476102", desc: "Venta al por menor de diarios y revistas en comercios especializados", cat: "Comercio minorista / retail" },
    { codigo: "477397", desc: "Venta al por menor de flores, plantas, arboles, semillas y abonos en comercios especializados", cat: "Comercio minorista / retail" },
    { codigo: "477310", desc: "Venta al por menor de gas licuado en bombonas (cilindros) en comercios especializados", cat: "Comercio minorista / retail" },
    { codigo: "476200", desc: "Venta al por menor de grabaciones de música y de video en comercios especializados", cat: "Comercio minorista / retail" },
    { codigo: "475902", desc: "Venta al por menor de instrumentos musicales en comercios especializados", cat: "Comercio minorista / retail" },
    { codigo: "476400", desc: "Venta al por menor de juegos y juguetes en comercios especializados", cat: "Comercio minorista / retail" },
    { codigo: "476101", desc: "Venta al por menor de libros en comercios especializados", cat: "Comercio minorista / retail" },
    { codigo: "477398", desc: "Venta al por menor de mascotas en comercios especializados", cat: "Comercio minorista / retail" },
    { codigo: "475901", desc: "Venta al por menor de muebles y colchones en comercios especializados", cat: "Comercio minorista / retail" },
    { codigo: "477409", desc: "Venta al por menor de otros artículos de segunda mano en comercios n.c.p.", cat: "Comercio minorista / retail" },
    { codigo: "476309", desc: "Venta al por menor de otros artículos y equipos de deporte n.c.p.", cat: "Comercio minorista / retail" },
    { codigo: "477399", desc: "Venta al por menor de otros productos en comercios especializados n.c.p.", cat: "Comercio minorista / retail" },
    { codigo: "475202", desc: "Venta al por menor de pinturas, barnices y lacas en comercios especializados", cat: "Comercio minorista / retail" },
    { codigo: "477102", desc: "Venta al por menor de prendas y accesorios de vestir en comercios especializados", cat: "Comercio minorista / retail" },
    { codigo: "475203", desc: "Venta al por menor de productos de vidrio en comercios especializados", cat: "Comercio minorista / retail" },
    { codigo: "477201", desc: "Venta al por menor de productos farmacéuticos y medicinales en comercios especializados", cat: "Comercio minorista / retail" },
    { codigo: "477396", desc: "Venta al por menor de recuerdos, artesanías y artículos religiosos en comercios especializados", cat: "Comercio minorista / retail" },
    { codigo: "477402", desc: "Venta al por menor de ropa usada en comercios", cat: "Comercio minorista / retail" },
    { codigo: "475100", desc: "Venta al por menor de telas, lanas, hilos y similares en comercios especializados", cat: "Comercio minorista / retail" },
    { codigo: "471100", desc: "Venta al por menor en comercios de alimentos, bebidas o tabaco (supermercados e hipermercados)", cat: "Comercio minorista / retail" },
    { codigo: "471910", desc: "Venta al por menor en comercios de vestuario y productos para el hogar (grandes tiendas)", cat: "Comercio minorista / retail" },
    { codigo: "472102", desc: "Venta al por menor en comercios especializados de carne y productos cárnicos", cat: "Comercio minorista / retail" },
    { codigo: "472103", desc: "Venta al por menor en comercios especializados de frutas y verduras (verdulerías)", cat: "Comercio minorista / retail" },
    { codigo: "472109", desc: "Venta al por menor en comercios especializados de huevos, confites y productos alimenticios n.c.p.", cat: "Comercio minorista / retail" },
    { codigo: "472104", desc: "Venta al por menor en comercios especializados de pescado, mariscos y productos conexos", cat: "Comercio minorista / retail" },
    { codigo: "472105", desc: "Venta al por menor en comercios especializados de productos de panadería y pastelería", cat: "Comercio minorista / retail" },
    { codigo: "479902", desc: "Venta al por menor mediante máquinas expendedoras", cat: "Comercio minorista / retail" },
    { codigo: "479903", desc: "Venta al por menor por comisionistas (no dependientes de comercios)", cat: "Comercio minorista / retail" },
    { codigo: "479100", desc: "Venta al por menor por correo, por Internet y vía telefónica", cat: "Comercio minorista / retail" },
    { codigo: "479901", desc: "Venta al por menor realizada por independientes en la locomoción colectiva (Ley 20.388)", cat: "Comercio minorista / retail" },
    { codigo: "421000", desc: "Construcción de carreteras y líneas de ferrocarril", cat: "Construcción" },
    { codigo: "410010", desc: "Construcción de edificios para uso residencial", cat: "Construcción" },
    { codigo: "431100", desc: "Demolición", cat: "Construcción" },
    { codigo: "432100", desc: "Instalaciones eléctricas", cat: "Construcción" },
    { codigo: "439000", desc: "Otras actividades especializadas de construcción", cat: "Construcción" },
    { codigo: "431200", desc: "Preparación del terreno", cat: "Construcción" },
    { codigo: "433000", desc: "Terminación y acabado de edificios", cat: "Construcción" },
    { codigo: "931201", desc: "Actividades de clubes de fútbol amateur y profesional", cat: "Deportes y recreación" },
    { codigo: "931209", desc: "Actividades de otros clubes deportivos n.c.p.", cat: "Deportes y recreación" },
    { codigo: "932100", desc: "Actividades de parques de atracciones y parques temáticos", cat: "Deportes y recreación" },
    { codigo: "931109", desc: "Gestión de otras instalaciones deportivas n.c.p.", cat: "Deportes y recreación" },
    { codigo: "932901", desc: "Gestión de salas de pool; gestión (explotación) de juegos electrónicos", cat: "Deportes y recreación" },
    { codigo: "931101", desc: "Hipódromos", cat: "Deportes y recreación" },
    { codigo: "932909", desc: "Otras actividades de esparcimiento y recreativas n.c.p.", cat: "Deportes y recreación" },
    { codigo: "931909", desc: "Otras actividades deportivas n.c.p.", cat: "Deportes y recreación" },
    { codigo: "931901", desc: "Promoción y organización de competencias deportivas", cat: "Deportes y recreación" },
    { codigo: "591300", desc: "Actividades de distribución de películas cinematográficas, videos y programas de televisión", cat: "Editoriales, audiovisual y radio" },
    { codigo: "591400", desc: "Actividades de exhibición de películas cinematográficas y cintas de video", cat: "Editoriales, audiovisual y radio" },
    { codigo: "592000", desc: "Actividades de grabación de sonido y edición de música", cat: "Editoriales, audiovisual y radio" },
    { codigo: "591100", desc: "Actividades de producción de películas cinematográficas, videos y programas de televisión", cat: "Editoriales, audiovisual y radio" },
    { codigo: "581300", desc: "Edición de diarios, revistas y otras publicaciones periódicas", cat: "Editoriales, audiovisual y radio" },
    { codigo: "581200", desc: "Edición de directorios y listas de correo", cat: "Editoriales, audiovisual y radio" },
    { codigo: "581100", desc: "Edición de libros", cat: "Editoriales, audiovisual y radio" },
    { codigo: "581900", desc: "Otras actividades de edición", cat: "Editoriales, audiovisual y radio" },
    { codigo: "602000", desc: "Programación y transmisiones de televisión", cat: "Editoriales, audiovisual y radio" },
    { codigo: "601000", desc: "Transmisiones de radio", cat: "Editoriales, audiovisual y radio" },
    { codigo: "854200", desc: "Enseñanza cultural", cat: "Educación" },
    { codigo: "854100", desc: "Enseñanza deportiva y recreativa", cat: "Educación" },
    { codigo: "850021", desc: "Enseñanza preescolar privada", cat: "Educación" },
    { codigo: "854901", desc: "Enseñanza preuniversitaria", cat: "Educación" },
    { codigo: "850022", desc: "Enseñanza primaria, secundaria científico humanista y técnico profesional privada", cat: "Educación" },
    { codigo: "853202", desc: "Enseñanza superior en centros de formación técnica", cat: "Educación" },
    { codigo: "853201", desc: "Enseñanza superior en institutos profesionales", cat: "Educación" },
    { codigo: "853120", desc: "Enseñanza superior en universidades privadas", cat: "Educación" },
    { codigo: "854909", desc: "Otros tipos de enseñanza n.c.p.", cat: "Educación" },
    { codigo: "854902", desc: "Servicios personales de educación", cat: "Educación" },
    { codigo: "351030", desc: "Distribución de energía eléctrica", cat: "Electricidad y gas" },
    { codigo: "353002", desc: "Elaboración de hielo (excepto fabricación de hielo seco)", cat: "Electricidad y gas" },
    { codigo: "352020", desc: "Fabricación de gas; distribución de combustibles gaseosos por tubería, excepto regasificación de GNL", cat: "Electricidad y gas" },
    { codigo: "351011", desc: "Generación de energía eléctrica en centrales hidroeléctricas", cat: "Electricidad y gas" },
    { codigo: "351012", desc: "Generación de energía eléctrica en centrales termoeléctricas", cat: "Electricidad y gas" },
    { codigo: "351019", desc: "Generación de energía eléctrica en otras centrales n.c.p.", cat: "Electricidad y gas" },
    { codigo: "353001", desc: "Suministro de vapor y de aire acondicionado", cat: "Electricidad y gas" },
    { codigo: "351020", desc: "Transmisión de energía eléctrica", cat: "Electricidad y gas" },
    { codigo: "781000", desc: "Actividades de agencias de empleo", cat: "Empleo y RR.HH." },
    { codigo: "783000", desc: "Otras actividades de dotación de recursos humanos", cat: "Empleo y RR.HH." },
    { codigo: "970000", desc: "Actividades de los hogares como empleadores de personal doméstico", cat: "Hogares como empleadores" },
    { codigo: "682000", desc: "Actividades inmobiliarias realizadas a cambio de una retribución o por contrata", cat: "Inmobiliario" },
    { codigo: "681011", desc: "Alquiler de bienes inmuebles amoblados o con equipos y maquinarias", cat: "Inmobiliario" },
    { codigo: "681012", desc: "Compra, venta y alquiler (excepto amoblados) de inmuebles", cat: "Inmobiliario" },
    { codigo: "721000", desc: "Investigaciones y desarrollo experimental en el campo de las ciencias naturales y la ingeniería", cat: "Investigación y desarrollo" },
    { codigo: "722000", desc: "Investigaciones y desarrollo experimental en el campo de las ciencias sociales y las humanidades", cat: "Investigación y desarrollo" },
    { codigo: "161000", desc: "Aserrado y acepilladura de madera", cat: "Madera" },
    { codigo: "162100", desc: "Fabricación de hojas de madera para enchapado y tableros a base de madera", cat: "Madera" },
    { codigo: "162900", desc: "Fabricación de otros productos de madera, de artículos de corcho, paja y materiales trenzables", cat: "Madera" },
    { codigo: "162200", desc: "Fabricación de partes y piezas de carpintería para edificios y construcciones", cat: "Madera" },
    { codigo: "162300", desc: "Fabricación de recipientes de madera", cat: "Madera" },
    { codigo: "325001", desc: "Actividades de laboratorios dentales", cat: "Manufactura diversa" },
    { codigo: "323000", desc: "Fabricación de artículos de deporte", cat: "Manufactura diversa" },
    { codigo: "310009", desc: "Fabricación de colchones; fabricación de otros muebles n.c.p.", cat: "Manufactura diversa" },
    { codigo: "322000", desc: "Fabricación de instrumentos musicales", cat: "Manufactura diversa" },
    { codigo: "325009", desc: "Fabricación de instrumentos y materiales médicos, oftalmológicos y odontológicos n.c.p.", cat: "Manufactura diversa" },
    { codigo: "321100", desc: "Fabricación de joyas y artículos conexos", cat: "Manufactura diversa" },
    { codigo: "324000", desc: "Fabricación de juegos y juguetes", cat: "Manufactura diversa" },
    { codigo: "310001", desc: "Fabricación de muebles principalmente de madera", cat: "Manufactura diversa" },
    { codigo: "329000", desc: "Otras industrias manufactureras n.c.p.", cat: "Manufactura diversa" },
    { codigo: "275000", desc: "Fabricación de aparatos de uso doméstico", cat: "Maquinaria y electrónica" },
    { codigo: "264000", desc: "Fabricación de aparatos electrónicos de consumo", cat: "Maquinaria y electrónica" },
    { codigo: "281400", desc: "Fabricación de cojinetes, engranajes, trenes de engranajes y piezas de transmisión", cat: "Maquinaria y electrónica" },
    { codigo: "261000", desc: "Fabricación de componentes y tableros electrónicos", cat: "Maquinaria y electrónica" },
    { codigo: "262000", desc: "Fabricación de computadores y equipo periférico", cat: "Maquinaria y electrónica" },
    { codigo: "263000", desc: "Fabricación de equipo de comunicaciones", cat: "Maquinaria y electrónica" },
    { codigo: "281600", desc: "Fabricación de equipo de elevación y manipulación", cat: "Maquinaria y electrónica" },
    { codigo: "265100", desc: "Fabricación de equipo de medición, prueba, navegación y control", cat: "Maquinaria y electrónica" },
    { codigo: "274000", desc: "Fabricación de equipo eléctrico de iluminación", cat: "Maquinaria y electrónica" },
    { codigo: "281500", desc: "Fabricación de hornos, calderas y quemadores", cat: "Maquinaria y electrónica" },
    { codigo: "267000", desc: "Fabricación de instrumentos ópticos y equipo fotográfico", cat: "Maquinaria y electrónica" },
    { codigo: "282100", desc: "Fabricación de maquinaria agropecuaria y forestal", cat: "Maquinaria y electrónica" },
    { codigo: "282300", desc: "Fabricación de maquinaria metalúrgica", cat: "Maquinaria y electrónica" },
    { codigo: "282200", desc: "Fabricación de maquinaria para la conformación de metales y de máquinas herramienta", cat: "Maquinaria y electrónica" },
    { codigo: "282500", desc: "Fabricación de maquinaria para la elaboración de alimentos, bebidas y tabaco", cat: "Maquinaria y electrónica" },
    { codigo: "282600", desc: "Fabricación de maquinaria para la elaboración de productos textiles, prendas de vestir y cueros", cat: "Maquinaria y electrónica" },
    { codigo: "282400", desc: "Fabricación de maquinaria para la explotación de minas y canteras y para obras de construcción", cat: "Maquinaria y electrónica" },
    { codigo: "281700", desc: "Fabricación de maquinaria y equipo de oficina (excepto computadores y equipo periférico)", cat: "Maquinaria y electrónica" },
    { codigo: "281100", desc: "Fabricación de motores y turbinas, excepto para aeronaves, vehículos automotores y motocicletas", cat: "Maquinaria y electrónica" },
    { codigo: "271000", desc: "Fabricación de motores, generadores y transformadores eléctricos, aparatos de distribución y control", cat: "Maquinaria y electrónica" },
    { codigo: "281300", desc: "Fabricación de otras bombas, compresores, grifos y válvulas", cat: "Maquinaria y electrónica" },
    { codigo: "273200", desc: "Fabricación de otros hilos y cables eléctricos", cat: "Maquinaria y electrónica" },
    { codigo: "279000", desc: "Fabricación de otros tipos de equipo eléctrico", cat: "Maquinaria y electrónica" },
    { codigo: "282900", desc: "Fabricación de otros tipos de maquinaria de uso especial", cat: "Maquinaria y electrónica" },
    { codigo: "281900", desc: "Fabricación de otros tipos de maquinaria de uso general", cat: "Maquinaria y electrónica" },
    { codigo: "272000", desc: "Fabricación de pilas, baterías y acumuladores", cat: "Maquinaria y electrónica" },
    { codigo: "265200", desc: "Fabricación de relojes", cat: "Maquinaria y electrónica" },
    { codigo: "252000", desc: "Fabricación de armas y municiones", cat: "Metálicas" },
    { codigo: "259300", desc: "Fabricación de artículos de cuchillería, herramientas de mano y artículos de ferretería", cat: "Metálicas" },
    { codigo: "251300", desc: "Fabricación de generadores de vapor, excepto calderas de agua caliente para calefacción central", cat: "Metálicas" },
    { codigo: "259900", desc: "Fabricación de otros productos elaborados de metal n.c.p.", cat: "Metálicas" },
    { codigo: "251100", desc: "Fabricación de productos metálicos para uso estructural", cat: "Metálicas" },
    { codigo: "242002", desc: "Fabricación de productos primarios de aluminio", cat: "Metálicas" },
    { codigo: "242001", desc: "Fabricación de productos primarios de cobre", cat: "Metálicas" },
    { codigo: "242009", desc: "Fabricación de productos primarios de metales preciosos y de otros metales no ferrosos n.c.p.", cat: "Metálicas" },
    { codigo: "251201", desc: "Fabricación de recipientes de metal para gases comprimidos o licuados", cat: "Metálicas" },
    { codigo: "251209", desc: "Fabricación de tanques, depósitos y recipientes de metal n.c.p.", cat: "Metálicas" },
    { codigo: "259100", desc: "Forja, prensado, estampado y laminado de metales; pulvimetalurgia", cat: "Metálicas" },
    { codigo: "243100", desc: "Fundición de hierro y acero", cat: "Metálicas" },
    { codigo: "243200", desc: "Fundición de metales no ferrosos", cat: "Metálicas" },
    { codigo: "241000", desc: "Industrias básicas de hierro y acero", cat: "Metálicas" },
    { codigo: "259200", desc: "Tratamiento y revestimiento de metales; maquinado", cat: "Metálicas" },
    { codigo: "239600", desc: "Corte, talla y acabado de la piedra", cat: "Minerales no metálicos" },
    { codigo: "239500", desc: "Fabricación de artículos de hormigón, cemento y yeso", cat: "Minerales no metálicos" },
    { codigo: "239400", desc: "Fabricación de cemento, cal y yeso", cat: "Minerales no metálicos" },
    { codigo: "231003", desc: "Fabricación de fibras de vidrio", cat: "Minerales no metálicos" },
    { codigo: "239200", desc: "Fabricación de materiales de construcción de arcilla", cat: "Minerales no metálicos" },
    { codigo: "239300", desc: "Fabricación de otros productos de porcelana y de cerámica", cat: "Minerales no metálicos" },
    { codigo: "239900", desc: "Fabricación de otros productos minerales no metálicos n.c.p.", cat: "Minerales no metálicos" },
    { codigo: "231009", desc: "Fabricación de productos de vidrio n.c.p.", cat: "Minerales no metálicos" },
    { codigo: "239100", desc: "Fabricación de productos refractarios", cat: "Minerales no metálicos" },
    { codigo: "231002", desc: "Fabricación de vidrio hueco", cat: "Minerales no metálicos" },
    { codigo: "231001", desc: "Fabricación de vidrio plano", cat: "Minerales no metálicos" },
    { codigo: "099001", desc: "Actividades de apoyo para la explotación de otras minas y canteras prestados por empresas", cat: "Minería" },
    { codigo: "099002", desc: "Actividades de apoyo para la explotación de otras minas y canteras prestados por profesionales", cat: "Minería" },
    { codigo: "091001", desc: "Actividades de apoyo para la extracción de petróleo y gas natural prestados por empresas", cat: "Minería" },
    { codigo: "089900", desc: "Explotación de otras minas y canteras n.c.p.", cat: "Minería" },
    { codigo: "051000", desc: "Extracción de carbón de piedra", cat: "Minería" },
    { codigo: "072992", desc: "Extracción de manganeso", cat: "Minería" },
    { codigo: "071000", desc: "Extracción de minerales de hierro", cat: "Minería" },
    { codigo: "072100", desc: "Extracción de minerales de uranio y torio", cat: "Minería" },
    { codigo: "089190", desc: "Extracción de minerales para la fabricación de abonos y productos químicos n.c.p.", cat: "Minería" },
    { codigo: "072910", desc: "Extracción de oro y plata", cat: "Minería" },
    { codigo: "072999", desc: "Extracción de otros minerales metalíferos no ferrosos n.c.p. (excepto zinc, plomo y manganeso)", cat: "Minería" },
    { codigo: "061000", desc: "Extracción de petróleo crudo", cat: "Minería" },
    { codigo: "081000", desc: "Extracción de piedra, arena y arcilla", cat: "Minería" },
    { codigo: "089300", desc: "Extracción de sal", cat: "Minería" },
    { codigo: "072991", desc: "Extracción de zinc y plomo", cat: "Minería" },
    { codigo: "089110", desc: "Extracción y procesamiento de litio", cat: "Minería" },
    { codigo: "990000", desc: "Actividades de organizaciones y órganos extraterritoriales", cat: "Otros" },
    { codigo: "040000", desc: "Extracción y procesamiento de cobre", cat: "Otros" },
    { codigo: "181200", desc: "Actividades de servicios relacionadas con la impresión", cat: "Papel e imprenta" },
    { codigo: "170110", desc: "Fabricación de celulosa y otras pastas de madera", cat: "Papel e imprenta" },
    { codigo: "170900", desc: "Fabricación de otros artículos de papel y cartón", cat: "Papel e imprenta" },
    { codigo: "170200", desc: "Fabricación de papel y cartón ondulado y de envases de papel y cartón", cat: "Papel e imprenta" },
    { codigo: "170190", desc: "Fabricación de papel y cartón para su posterior uso industrial n.c.p.", cat: "Papel e imprenta" },
    { codigo: "181101", desc: "Impresión de libros", cat: "Papel e imprenta" },
    { codigo: "181109", desc: "Otras actividades de impresión n.c.p.", cat: "Papel e imprenta" },
    { codigo: "182000", desc: "Reproducción de grabaciones", cat: "Papel e imprenta" },
    { codigo: "732000", desc: "Estudios de mercado y encuestas de opinión pública", cat: "Publicidad e investigación de mercado" },
    { codigo: "731001", desc: "Servicios de publicidad prestados por empresas", cat: "Publicidad e investigación de mercado" },
    { codigo: "731002", desc: "Servicios de publicidad prestados por profesionales", cat: "Publicidad e investigación de mercado" },
    { codigo: "201200", desc: "Fabricación de abonos y compuestos de nitrógeno", cat: "Químicos, plástico, caucho" },
    { codigo: "201101", desc: "Fabricación de carbón vegetal (excepto activado); fabricación de briquetas de carbón vegetal", cat: "Químicos, plástico, caucho" },
    { codigo: "221100", desc: "Fabricación de cubiertas y cámaras de caucho; recauchutado y renovación de cubiertas de caucho", cat: "Químicos, plástico, caucho" },
    { codigo: "202901", desc: "Fabricación de explosivos y productos pirotécnicos", cat: "Químicos, plástico, caucho" },
    { codigo: "203000", desc: "Fabricación de fibras artificiales", cat: "Químicos, plástico, caucho" },
    { codigo: "202300", desc: "Fabricación de jabones y detergentes, preparados para limpiar, perfumes y preparados de tocador", cat: "Químicos, plástico, caucho" },
    { codigo: "201109", desc: "Fabricación de otras sustancias químicas básicas n.c.p.", cat: "Químicos, plástico, caucho" },
    { codigo: "221900", desc: "Fabricación de otros productos de caucho", cat: "Químicos, plástico, caucho" },
    { codigo: "202909", desc: "Fabricación de otros productos químicos n.c.p.", cat: "Químicos, plástico, caucho" },
    { codigo: "202200", desc: "Fabricación de pinturas, barnices y productos de revestimiento, tintas de imprenta y masillas", cat: "Químicos, plástico, caucho" },
    { codigo: "202100", desc: "Fabricación de plaguicidas y otros productos químicos de uso agropecuario", cat: "Químicos, plástico, caucho" },
    { codigo: "201300", desc: "Fabricación de plásticos y caucho sintético en formas primarias", cat: "Químicos, plástico, caucho" },
    { codigo: "191000", desc: "Fabricación de productos de hornos de coque", cat: "Químicos, plástico, caucho" },
    { codigo: "192000", desc: "Fabricación de productos de la refinación del petróleo", cat: "Químicos, plástico, caucho" },
    { codigo: "222000", desc: "Fabricación de productos de plástico", cat: "Químicos, plástico, caucho" },
    { codigo: "210000", desc: "Fabricación de productos farmacéuticos, sustancias químicas medicinales y productos botánicos", cat: "Químicos, plástico, caucho" },
    { codigo: "952200", desc: "Reparación de aparatos de uso doméstico, equipo doméstico y de jardinería", cat: "Reparaciones" },
    { codigo: "952300", desc: "Reparación de calzado y de artículos de cuero", cat: "Reparaciones" },
    { codigo: "951100", desc: "Reparación de computadores y equipo periférico", cat: "Reparaciones" },
    { codigo: "951200", desc: "Reparación de equipo de comunicaciones (incluye la reparación teléfonos celulares)", cat: "Reparaciones" },
    { codigo: "952900", desc: "Reparación de otros efectos personales y enseres domésticos", cat: "Reparaciones" },
    { codigo: "331502", desc: "Reparación de aeronaves y naves espaciales", cat: "Reparación de maquinaria" },
    { codigo: "331501", desc: "Reparación de buques, embarcaciones menores y estructuras flotantes", cat: "Reparación de maquinaria" },
    { codigo: "331301", desc: "Reparación de equipo de medición, prueba, navegación y control", cat: "Reparación de maquinaria" },
    { codigo: "331400", desc: "Reparación de equipo eléctrico (excepto reparación de equipo y enseres domésticos)", cat: "Reparación de maquinaria" },
    { codigo: "331201", desc: "Reparación de maquinaria agropecuaria y forestal", cat: "Reparación de maquinaria" },
    { codigo: "331202", desc: "Reparación de maquinaria metalúrgica, para la minería, extracción de petróleo y para la construcción", cat: "Reparación de maquinaria" },
    { codigo: "331203", desc: "Reparación de maquinaria para la elaboración de alimentos, bebidas y tabaco", cat: "Reparación de maquinaria" },
    { codigo: "331204", desc: "Reparación de maquinaria para producir textiles, prendas de vestir, artículos de cuero y calzado", cat: "Reparación de maquinaria" },
    { codigo: "331209", desc: "Reparación de otro tipo de maquinaria y equipos industriales n.c.p.", cat: "Reparación de maquinaria" },
    { codigo: "331309", desc: "Reparación de otros equipos electrónicos y ópticos n.c.p.", cat: "Reparación de maquinaria" },
    { codigo: "331100", desc: "Reparación de productos elaborados de metal", cat: "Reparación de maquinaria" },
    { codigo: "563001", desc: "Actividades de discotecas y cabaret (night club), con predominio del servicio de bebidas", cat: "Restaurantes y alimentación" },
    { codigo: "561000", desc: "Actividades de restaurantes y de servicio móvil de comidas", cat: "Restaurantes y alimentación" },
    { codigo: "562100", desc: "Suministro de comidas por encargo (Servicios de banquetería)", cat: "Restaurantes y alimentación" },
    { codigo: "562900", desc: "Suministro industrial de comidas por encargo; concesión de servicios de alimentación", cat: "Restaurantes y alimentación" },
    { codigo: "861020", desc: "Actividades de hospitales y clínicas privadas", cat: "Salud y asistencia social" },
    { codigo: "869010", desc: "Actividades de laboratorios clínicos y bancos de sangre", cat: "Salud y asistencia social" },
    { codigo: "862022", desc: "Centros de atención odontológica privados (establecimientos de atención ambulatoria)", cat: "Salud y asistencia social" },
    { codigo: "862021", desc: "Centros médicos privados (establecimientos de atención ambulatoria)", cat: "Salud y asistencia social" },
    { codigo: "889000", desc: "Otras actividades de asistencia social sin alojamiento", cat: "Salud y asistencia social" },
    { codigo: "879000", desc: "Otras actividades de atención en instituciones", cat: "Salud y asistencia social" },
    { codigo: "869091", desc: "Otros servicios de atención de la salud humana prestados por empresas", cat: "Salud y asistencia social" },
    { codigo: "862031", desc: "Servicios de médicos prestados de forma independiente", cat: "Salud y asistencia social" },
    { codigo: "862032", desc: "Servicios de odontólogos prestados de forma independiente", cat: "Salud y asistencia social" },
    { codigo: "869092", desc: "Servicios prestados de forma independiente por otros profesionales de la salud", cat: "Salud y asistencia social" },
    { codigo: "803000", desc: "Actividades de investigación (incluye actividades de investigadores y detectives privados)", cat: "Seguridad e investigación" },
    { codigo: "801002", desc: "Servicio de transporte de valores en vehículos blindados", cat: "Seguridad e investigación" },
    { codigo: "801003", desc: "Servicios de seguridad privada prestados por independientes", cat: "Seguridad e investigación" },
    { codigo: "812901", desc: "Desratización, desinfección y exterminio de plagas no agrícolas", cat: "Servicios a edificios y limpieza" },
    { codigo: "812100", desc: "Limpieza general de edificios", cat: "Servicios a edificios y limpieza" },
    { codigo: "812909", desc: "Otras actividades de limpieza de edificios e instalaciones industriales n.c.p.", cat: "Servicios a edificios y limpieza" },
    { codigo: "829120", desc: "Actividades de agencias de calificación crediticia", cat: "Servicios administrativos de oficina" },
    { codigo: "829110", desc: "Actividades de agencias de cobro", cat: "Servicios administrativos de oficina" },
    { codigo: "822000", desc: "Actividades de call-center", cat: "Servicios administrativos de oficina" },
    { codigo: "829200", desc: "Actividades de envasado y empaquetado", cat: "Servicios administrativos de oficina" },
    { codigo: "821900", desc: "Fotocopiado, preparación de documentos y otras actividades especializadas de apoyo de oficina", cat: "Servicios administrativos de oficina" },
    { codigo: "823000", desc: "Organización de convenciones y exposiciones comerciales", cat: "Servicios administrativos de oficina" },
    { codigo: "829900", desc: "Otras actividades de servicios de apoyo a las empresas n.c.p.", cat: "Servicios administrativos de oficina" },
    { codigo: "639100", desc: "Actividades de agencias de noticias", cat: "Servicios de informática" },
    { codigo: "620200", desc: "Actividades de consultoría de informática y de gestión de instalaciones informáticas", cat: "Servicios de informática" },
    { codigo: "620100", desc: "Actividades de programación informática", cat: "Servicios de informática" },
    { codigo: "631100", desc: "Procesamiento de datos, hospedaje y actividades conexas", cat: "Servicios de informática" },
    { codigo: "641910", desc: "Actividades bancarias", cat: "Servicios financieros y seguros" },
    { codigo: "651220", desc: "Actividades de Isapres", cat: "Servicios financieros y seguros" },
    { codigo: "662200", desc: "Actividades de agentes y corredores de seguros", cat: "Servicios financieros y seguros" },
    { codigo: "661204", desc: "Actividades de casas de cambio y operadores de divisa", cat: "Servicios financieros y seguros" },
    { codigo: "661904", desc: "Actividades de clasificadoras de riesgo", cat: "Servicios financieros y seguros" },
    { codigo: "649202", desc: "Actividades de crédito prendario", cat: "Servicios financieros y seguros" },
    { codigo: "661901", desc: "Actividades de cámaras de compensación", cat: "Servicios financieros y seguros" },
    { codigo: "661201", desc: "Actividades de securitizadoras", cat: "Servicios financieros y seguros" },
    { codigo: "661100", desc: "Administración de mercados financieros", cat: "Servicios financieros y seguros" },
    { codigo: "661902", desc: "Administración de tarjetas de crédito", cat: "Servicios financieros y seguros" },
    { codigo: "663010", desc: "Administradoras de Fondos de Pensiones (AFP)", cat: "Servicios financieros y seguros" },
    { codigo: "663093", desc: "Administradoras de fices (fondos de inversión de capital extranjero)", cat: "Servicios financieros y seguros" },
    { codigo: "663091", desc: "Administradoras de fondos de inversión", cat: "Servicios financieros y seguros" },
    { codigo: "663092", desc: "Administradoras de fondos mutuos", cat: "Servicios financieros y seguros" },
    { codigo: "663094", desc: "Administradoras de fondos para la vivienda", cat: "Servicios financieros y seguros" },
    { codigo: "663099", desc: "Administradoras de fondos para otros fines n.c.p.", cat: "Servicios financieros y seguros" },
    { codigo: "661203", desc: "Agentes de valores", cat: "Servicios financieros y seguros" },
    { codigo: "641100", desc: "Banca central", cat: "Servicios financieros y seguros" },
    { codigo: "649203", desc: "Cajas de compensación", cat: "Servicios financieros y seguros" },
    { codigo: "661202", desc: "Corredores de bolsa", cat: "Servicios financieros y seguros" },
    { codigo: "661903", desc: "Empresas de asesoría y consultoría en inversión financiera; sociedades de apoyo al giro", cat: "Servicios financieros y seguros" },
    { codigo: "662100", desc: "Evaluación de riesgos y daños (incluye actividades de liquidadores de seguros)", cat: "Servicios financieros y seguros" },
    { codigo: "649201", desc: "Financieras", cat: "Servicios financieros y seguros" },
    { codigo: "643000", desc: "Fondos y sociedades de inversión y entidades financieras similares", cat: "Servicios financieros y seguros" },
    { codigo: "649100", desc: "Leasing financiero", cat: "Servicios financieros y seguros" },
    { codigo: "662900", desc: "Otras actividades auxiliares de las actividades de seguros y fondos de pensiones", cat: "Servicios financieros y seguros" },
    { codigo: "661909", desc: "Otras actividades auxiliares de las actividades de servicios financieros n.c.p.", cat: "Servicios financieros y seguros" },
    { codigo: "649209", desc: "Otras actividades de concesión de crédito n.c.p.", cat: "Servicios financieros y seguros" },
    { codigo: "649900", desc: "Otras actividades de servicios financieros, excepto las de seguros y fondos de pensiones n.c.p.", cat: "Servicios financieros y seguros" },
    { codigo: "661209", desc: "Otros servicios de corretaje de valores y commodities n.c.p.", cat: "Servicios financieros y seguros" },
    { codigo: "641990", desc: "Otros tipos de intermediación monetaria n.c.p.", cat: "Servicios financieros y seguros" },
    { codigo: "652000", desc: "Reaseguros", cat: "Servicios financieros y seguros" },
    { codigo: "651100", desc: "Seguros de vida", cat: "Servicios financieros y seguros" },
    { codigo: "651210", desc: "Seguros generales, excepto actividades de Isapres", cat: "Servicios financieros y seguros" },
    { codigo: "960902", desc: "Actividades de salones de masajes, baños turcos, saunas, servicio de baños públicos", cat: "Servicios personales (peluquería, lavandería, otros)" },
    { codigo: "960100", desc: "Lavado y limpieza, incluida la limpieza en seco, de productos textiles y de piel", cat: "Servicios personales (peluquería, lavandería, otros)" },
    { codigo: "960909", desc: "Otras actividades de servicios personales n.c.p.", cat: "Servicios personales (peluquería, lavandería, otros)" },
    { codigo: "960200", desc: "Peluquería y otros tratamientos de belleza", cat: "Servicios personales (peluquería, lavandería, otros)" },
    { codigo: "960901", desc: "Servicios de adiestramiento, guardería, peluquería, paseo de mascotas (excepto act. veterinarias)", cat: "Servicios personales (peluquería, lavandería, otros)" },
    { codigo: "960320", desc: "Servicios de cementerios", cat: "Servicios personales (peluquería, lavandería, otros)" },
    { codigo: "960310", desc: "Servicios funerarios", cat: "Servicios personales (peluquería, lavandería, otros)" },
    { codigo: "702000", desc: "Actividades de consultoría de gestión", cat: "Servicios profesionales (legal, contable, consultoría)" },
    { codigo: "692000", desc: "Actividades de contabilidad, teneduría de libros y auditoría; consultoría fiscal", cat: "Servicios profesionales (legal, contable, consultoría)" },
    { codigo: "691003", desc: "Conservador de bienes raíces", cat: "Servicios profesionales (legal, contable, consultoría)" },
    { codigo: "691004", desc: "Receptores judiciales", cat: "Servicios profesionales (legal, contable, consultoría)" },
    { codigo: "691002", desc: "Servicio notarial", cat: "Servicios profesionales (legal, contable, consultoría)" },
    { codigo: "691009", desc: "Servicios de arbitraje; síndicos de quiebra y peritos judiciales; otras actividades jurídicas n.c.p.", cat: "Servicios profesionales (legal, contable, consultoría)" },
    { codigo: "691001", desc: "Servicios de asesoramiento y representación jurídica", cat: "Servicios profesionales (legal, contable, consultoría)" },
    { codigo: "741001", desc: "Actividades de diseño de vestuario", cat: "Servicios profesionales diversos" },
    { codigo: "741002", desc: "Actividades de diseño y decoración de interiores", cat: "Servicios profesionales diversos" },
    { codigo: "749001", desc: "Asesoría y gestión en la compra o venta de pequeñas y medianas empresas", cat: "Servicios profesionales diversos" },
    { codigo: "741009", desc: "Otras actividades especializadas de diseño n.c.p.", cat: "Servicios profesionales diversos" },
    { codigo: "749009", desc: "Otras actividades profesionales, científicas y técnicas n.c.p.", cat: "Servicios profesionales diversos" },
    { codigo: "742001", desc: "Servicios de revelado, impresión y ampliación de fotografías", cat: "Servicios profesionales diversos" },
    { codigo: "749002", desc: "Servicios de traducción e interpretación prestados por empresas", cat: "Servicios profesionales diversos" },
    { codigo: "742003", desc: "Servicios personales de fotografía", cat: "Servicios profesionales diversos" },
    { codigo: "749003", desc: "Servicios personales de traducción e interpretación", cat: "Servicios profesionales diversos" },
    { codigo: "742002", desc: "Servicios y actividades de fotografía", cat: "Servicios profesionales diversos" },
    { codigo: "619010", desc: "Centros de llamados y centros de acceso a Internet", cat: "Telecomunicaciones" },
    { codigo: "619090", desc: "Otras actividades de telecomunicaciones n.c.p.", cat: "Telecomunicaciones" },
    { codigo: "611090", desc: "Otros servicios de telecomunicaciones alámbricas n.c.p.", cat: "Telecomunicaciones" },
    { codigo: "611010", desc: "Telefonía fija", cat: "Telecomunicaciones" },
    { codigo: "611020", desc: "Telefonía larga distancia", cat: "Telecomunicaciones" },
    { codigo: "612010", desc: "Telefonía móvil celular", cat: "Telecomunicaciones" },
    { codigo: "613020", desc: "Televisión de pago satelital", cat: "Telecomunicaciones" },
    { codigo: "131300", desc: "Acabado de productos textiles", cat: "Textil, vestuario y cuero" },
    { codigo: "151100", desc: "Curtido y adobo de cueros; adobo y teñido de pieles", cat: "Textil, vestuario y cuero" },
    { codigo: "141003", desc: "Fabricación de accesorios de vestir", cat: "Textil, vestuario y cuero" },
    { codigo: "139200", desc: "Fabricación de artículos confeccionados de materiales textiles, excepto prendas de vestir", cat: "Textil, vestuario y cuero" },
    { codigo: "143000", desc: "Fabricación de artículos de punto y ganchillo", cat: "Textil, vestuario y cuero" },
    { codigo: "152000", desc: "Fabricación de calzado", cat: "Textil, vestuario y cuero" },
    { codigo: "139400", desc: "Fabricación de cuerdas, cordeles, bramantes y redes", cat: "Textil, vestuario y cuero" },
    { codigo: "151200", desc: "Fabricación de maletas, bolsos y artículos similares, artículos de talabartería y guarnicionería", cat: "Textil, vestuario y cuero" },
    { codigo: "139900", desc: "Fabricación de otros productos textiles n.c.p.", cat: "Textil, vestuario y cuero" },
    { codigo: "141002", desc: "Fabricación de prendas de vestir de cuero natural o artificial", cat: "Textil, vestuario y cuero" },
    { codigo: "141001", desc: "Fabricación de prendas de vestir de materiales textiles y similares", cat: "Textil, vestuario y cuero" },
    { codigo: "141004", desc: "Fabricación de ropa de trabajo", cat: "Textil, vestuario y cuero" },
    { codigo: "139300", desc: "Fabricación de tapices y alfombras", cat: "Textil, vestuario y cuero" },
    { codigo: "131200", desc: "Tejedura de productos textiles", cat: "Textil, vestuario y cuero" },
    { codigo: "532000", desc: "Actividades de mensajería", cat: "Transporte y almacenamiento" },
    { codigo: "522200", desc: "Actividades de servicios vinculadas al transporte acuático", cat: "Transporte y almacenamiento" },
    { codigo: "522190", desc: "Actividades de servicios vinculadas al transporte terrestre n.c.p.", cat: "Transporte y almacenamiento" },
    { codigo: "531000", desc: "Actividades postales", cat: "Transporte y almacenamiento" },
    { codigo: "522910", desc: "Agencias de aduanas", cat: "Transporte y almacenamiento" },
    { codigo: "522120", desc: "Explotación de estacionamientos de vehículos automotores y parquímetros", cat: "Transporte y almacenamiento" },
    { codigo: "521001", desc: "Explotación de frigoríficos para almacenamiento y depósito", cat: "Transporte y almacenamiento" },
    { codigo: "522110", desc: "Explotación de terminales terrestres de pasajeros", cat: "Transporte y almacenamiento" },
    { codigo: "522400", desc: "Manipulación de la carga", cat: "Transporte y almacenamiento" },
    { codigo: "522990", desc: "Otras actividades de apoyo al transporte n.c.p.", cat: "Transporte y almacenamiento" },
    { codigo: "492290", desc: "Otras actividades de transporte de pasajeros por vía terrestre n.c.p.", cat: "Transporte y almacenamiento" },
    { codigo: "493090", desc: "Otras actividades de transporte por tuberías n.c.p.", cat: "Transporte y almacenamiento" },
    { codigo: "521009", desc: "Otros servicios de almacenamiento y depósito n.c.p.", cat: "Transporte y almacenamiento" },
    { codigo: "492240", desc: "Servicios de transporte a turistas", cat: "Transporte y almacenamiento" },
    { codigo: "492210", desc: "Servicios de transporte de escolares", cat: "Transporte y almacenamiento" },
    { codigo: "492230", desc: "Servicios de transporte de pasajeros en taxis libres y radiotaxis", cat: "Transporte y almacenamiento" },
    { codigo: "492220", desc: "Servicios de transporte de trabajadores", cat: "Transporte y almacenamiento" },
    { codigo: "522130", desc: "Servicios prestados por concesionarios de carreteras", cat: "Transporte y almacenamiento" },
    { codigo: "501200", desc: "Transporte de carga marítimo y de cabotaje", cat: "Transporte y almacenamiento" },
    { codigo: "492300", desc: "Transporte de carga por carretera", cat: "Transporte y almacenamiento" },
    { codigo: "491200", desc: "Transporte de carga por ferrocarril", cat: "Transporte y almacenamiento" },
    { codigo: "512000", desc: "Transporte de carga por vía aérea", cat: "Transporte y almacenamiento" },
    { codigo: "502200", desc: "Transporte de carga por vías de navegación interiores", cat: "Transporte y almacenamiento" },
    { codigo: "492250", desc: "Transporte de pasajeros en buses interurbanos", cat: "Transporte y almacenamiento" },
    { codigo: "501100", desc: "Transporte de pasajeros marítimo y de cabotaje", cat: "Transporte y almacenamiento" },
    { codigo: "511000", desc: "Transporte de pasajeros por vía aérea", cat: "Transporte y almacenamiento" },
    { codigo: "502100", desc: "Transporte de pasajeros por vías de navegación interiores", cat: "Transporte y almacenamiento" },
    { codigo: "492130", desc: "Transporte de pasajeros vía taxi colectivo", cat: "Transporte y almacenamiento" },
    { codigo: "491100", desc: "Transporte interurbano de pasajeros por ferrocarril", cat: "Transporte y almacenamiento" },
    { codigo: "492120", desc: "Transporte urbano y suburbano de pasajeros vía locomoción colectiva", cat: "Transporte y almacenamiento" },
    { codigo: "492110", desc: "Transporte urbano y suburbano de pasajeros vía metro y metrotren", cat: "Transporte y almacenamiento" },
    { codigo: "791100", desc: "Actividades de agencias de viajes", cat: "Turismo y agencias de viajes" },
    { codigo: "799000", desc: "Otros servicios de reservas y actividades conexas (incluye venta de entradas para teatro, y otros)", cat: "Turismo y agencias de viajes" },
    { codigo: "301100", desc: "Construcción de buques, embarcaciones menores y estructuras flotantes", cat: "Vehículos y transporte (fabricación)" },
    { codigo: "301200", desc: "Construcción de embarcaciones de recreo y de deporte", cat: "Vehículos y transporte (fabricación)" },
    { codigo: "303000", desc: "Fabricación de aeronaves, naves espaciales y maquinaria conexa", cat: "Vehículos y transporte (fabricación)" },
    { codigo: "309200", desc: "Fabricación de bicicletas y de sillas de ruedas", cat: "Vehículos y transporte (fabricación)" },
    { codigo: "292000", desc: "Fabricación de carrocerías para vehículos automotores; fabricación de remolques y semirremolques", cat: "Vehículos y transporte (fabricación)" },
    { codigo: "302000", desc: "Fabricación de locomotoras y material rodante", cat: "Vehículos y transporte (fabricación)" },
    { codigo: "309100", desc: "Fabricación de motocicletas", cat: "Vehículos y transporte (fabricación)" },
    { codigo: "309900", desc: "Fabricación de otros tipos de equipo de transporte n.c.p.", cat: "Vehículos y transporte (fabricación)" },
    { codigo: "293000", desc: "Fabricación de partes, piezas y accesorios para vehículos automotores", cat: "Vehículos y transporte (fabricación)" },
    { codigo: "291000", desc: "Fabricación de vehículos automotores", cat: "Vehículos y transporte (fabricación)" },
    { codigo: "750001", desc: "Actividades de clínicas veterinarias", cat: "Veterinaria" },
    { codigo: "750002", desc: "Actividades de veterinarios, técnicos y otro personal auxiliar, prestados de forma independiente", cat: "Veterinaria" }
  ];

  const CATEGORIAS = Array.from(new Set(GIROS.map(g => g.cat))).sort((a, b) => a.localeCompare(b, 'es'));

  function normalizar(s) {
    return String(s || '').toLowerCase()
      .normalize('NFD').replace(/[\u0300-\u036f]/g, '');
  }

  function buscar(query, limit) {
    const q = normalizar(query).trim();
    if (!q) return GIROS.slice(0, limit || 30);
    const max = limit || 30;
    const matches = [];
    for (const g of GIROS) {
      const desc = normalizar(g.desc);
      const cat = normalizar(g.cat);
      if (desc.startsWith(q)) matches.push({ g, score: 100 });
      else if (desc.includes(q)) matches.push({ g, score: 50 });
      else if (cat.includes(q)) matches.push({ g, score: 20 });
      else if (g.codigo.startsWith(q)) matches.push({ g, score: 80 });
      if (matches.length >= max * 3) break;
    }
    matches.sort((a, b) => b.score - a.score);
    return matches.slice(0, max).map(m => m.g);
  }

  function buscarPorCodigo(codigo) {
    const c = String(codigo || '').trim();
    return GIROS.find(g => g.codigo === c) || null;
  }

  window.GirosSII = { GIROS, CATEGORIAS, buscar, buscarPorCodigo };
})();
